callbacks:
  early_stopping:
    monitor: val/loss
    patience: 5
    mode: min
  model_checkpoint:
    monitor: val/loss
    mode: min
    save_top_k: 1
    save_last: true
    filename: best
  lr_monitor:
    logging_interval: epoch
